import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { AuthProvider } from "@/AuthContext";
import TanstackProvider from "../../providers/TankstackProvider";
import { Toaster } from "./components/ui/toaster";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Data Capturing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body className={""}>
        <AuthProvider>
          <TanstackProvider>
            {/* <SubdomainProvider> */}
               {/* <PermissionsProvider> */}
                 <main>{children}</main>
               {/* </PermissionsProvider> */}
            {/* </SubdomainProvider> */}
             <Toaster />
           </TanstackProvider>
         </AuthProvider>
       </body>
       <script
        src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"
        async
      ></script>
    </html>
  );
}



// import { PermissionsProvider } from "@/api/hooks/usePermissions";
// import { SubdomainProvider } from "@/api/hooks/useUrl";



// import { AuthProvider } from "@/AuthContext";
// import { Toaster } from "@/app/components/ui/toaster";
// import localFont from "next/font/local";
// import TanstackProvider from "../../providers/TankstackProvider";
// import "./globals.css";



// export const metadata = {
//   title: "Data Capturing",
//   description: "AI + Gamification",
//   openGraph: {
//     title: "Data Capturing",
//     description: "AI + Gamification",
//     type: "website",
//     url: "https://gamai.com.ng",
//     images: [
//       {
//         url: "/gamai2.png", // Default image
//         width: 1200,
//         height: 630,
//         alt: "Course Preview Image",
//       },
//     ],
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={""}>
//         <AuthProvider>
//           <TanstackProvider>
//             {/* <SubdomainProvider> */}
//               {/* <PermissionsProvider> */}
//                 <main>{children}</main>
//               {/* </PermissionsProvider> */}
//             {/* </SubdomainProvider> */}
//             <Toaster />
//           </TanstackProvider>
//         </AuthProvider>
//       </body>
//       <script
//         src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"
//         async
//       ></script>
//     </html>
//   );
// }
